# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  android: circleci/android@2.5.0
  flutter: circleci/flutter@2.0.4
  gcp-cli: circleci/gcp-cli@3.1.1

# Define a job to be invoked later in a workflow.
jobs:
  build-app:
    executor:
      name: android/android-machine
      resource-class: medium
    
    steps:
      - checkout

      - flutter/install_sdk: 
          version: 3.7.0

      - flutter/install_pub:
          cache-version: v1

      - run:
          name: Flutter pub get
          command: |
            flutter pub get

      - run:
          name: Build APK
          command: |
            flutter build apk

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
    
  deliver-app:
    executor: gcp-cli/default
    steps:
      - run:
          name: Get service account
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > /home/circleci/gcloud-service-key.json
            export GOOGLE_SERVICES_JSON="$GCLOUD_SERVICE_KEY"
            echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json
      - gcp-cli/setup:
          version: 404.0.0
      - run:
          name: Setup Google services
          command: |
            gcloud auth activate-service-account --key-file=/home/circleci/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Upload file to Cloud Storage
          command: |
            current_date=$(date +'%Y%m%d')
            # full_apk_name=$APK_NAME-$current_date.apk
            full_apk_name=hello.txt
            echo "hi" > $full_apk_name
            gsutil cp $full_apk_name gs://$BUCKET_OBJECT_PATH/$full_apk_name
            # gsutil cp build/app/outputs/flutter-apk/app-release.apk gs://$BUCKET_OBJECT_PATH/$full_apk_name
            gsutil acl ch -u AllUsers:R gs://$BUCKET_OBJECT_PATH/$full_apk_name

# Orchestrate jobs using workflows
workflows:
  build-the-app:
    jobs:
      # - build-app
      - deliver-app
      #     requires:
      #       - build-app