# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  android: circleci/android@2.5.0
  flutter: circleci/flutter@2.0.4
  gcp-cli: circleci/gcp-cli@3.1.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: 2024.01.1
    
    steps:
      - checkout

      # - flutter/install_sdk: 
      #     version: 3.7.0

      # - flutter/install_pub:
      #     cache-version: v1

      # - run:
      #     name: Flutter pub get
      #     command: |
      #       flutter pub get

      - run:
          name: Build APK
          command: |
            # flutter build apk
            pwd
            ls
            mkdir build
            echo "hi" > build/echo-output.txt

      - store_artifacts:
          path: build/echo-output.txt

      # - store_artifacts:
      #     path: build/app/outputs/flutter-apk/app-release.apk
    
  deliver:
    executor: gcp-cli/default

    resource_class: small

    steps:
      # - gcp-cli/setup:
      #     version: 404.0.0
      # - run:
      #     name: Setup Google services
      #     command: |
            # echo "$GCLOUD_SERVICE_KEY" | base64 --decode > /home/circleci/gcloud-service-key.json
            # gcloud auth activate-service-account --key-file=/home/circleci/gcloud-service-key.json
            # gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - run:
          name: Upload file to Cloud Storage
          command: |
            pwd
            ls
            current_date=$(date +'%Y%m%d')
            full_apk_name=$APK_NAME-$current_date.apk
            # ls build
            gsutil cp build/app/outputs/flutter-apk/app-release.apk gs://$BUCKET_OBJECT_PATH/$full_apk_name
            gsutil acl ch -u AllUsers:R gs://$BUCKET_OBJECT_PATH/$full_apk_name

# Orchestrate jobs using workflows
workflows:
  build-the-app:
    jobs:
      - build
      - deliver:
          requires:
            - build